### PR TITLE
September 2021 meeting notes

### PR DESCRIPTION
**Pull request by jessemapel**

### CODE REVIEW

**Review by michaelaye — COMMENTED** [review]
who was attending?

**Comment by jessemapel** [comment]
@michaelaye The attending list is on the September meeting notes, at the top. I don't think I missed anyone.

**Comment by jessemapel** [comment]
Can this get reviewed so it can be merged?

**Comment by michaelaye** [comment]
ah, i reviewed 5667c83 alone which didn't have the attendees? What did I click wrong that I only saw the 5667c83 specific changes instead of everything?

**Review by michaelaye — APPROVED** [review]

**Comment by michaelaye** [comment]
i guess i clicked on that commit instead of "Review changes", sorry for the confusion.

**Pull request merged**
