### PR TITLE
November release meeting notes

### PR DESCRIPTION
**Pull request by jessemapel**
I made a new working group directory and then made a release directory under that for release stuff. If anyone has thoughts about how best to handle working group documents please share them here.

### CODE REVIEW

**Comment by KrisBecker** [comment]
Hi All...

Just had an all-hands UA/OREX meeting changed to the same day/time as our Dec 11 10am meeting. If we can change our meeting to later or earlier that day, that would be great.

**Comment by jessemapel** [comment]
I would be able to do later that day any time.

**Comment by astrostu** [comment]
I can do later that day, but not earlier.

**Comment by jessemapel** [comment]
How about we move it to Friday at 2PM?

**Comment by audiefen** [comment]
Can we make it Friday 1 pm or 3 pm? I have a conflict at 2 pm.

**Comment by jessemapel** [comment]
@audiefen @astrostu Kris just notified me that he's going to be unable to make it Friday. So, let's stick to the original Friday at 10am time slot and he can loop back in with us at the next meeting.

**Comment by astrostu** [comment]
Is that Friday, 10am MST, the 18th of December?  Or the 11th?

**Comment by jessemapel** [comment]
@astrostu This Friday the 11th at 10 MST, we'll use the same teams link as before.

**Comment by astrostu** [comment]
So, it's Friday the 11th at 10:03 MST, I don't see anyone on the Meetings link.   Tried both the December and November one.

**Comment by victoronline** [comment]
Are we still meeting?

Victor Silva
Research Software Engineer
pronouns: He | Him | Él
*Lunar Reconnaissance Orbiter Camera (LROC <https://www.lroc.asu.edu/>)*
*School of Earth and Space Exploration** | **Arizona State University *

Tempe, Arizona | 85287

phone: 602-369-0363 <602.369.0363>

**Comment by jessemapel** [comment]
@astrostu I just realized, these meeting notes are for the release working group and not the full ISIS TC. You didn't need to attend today, the full ISIS TC meeting is next week see: https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/meetings/2020-12-15.md

Thanks for getting on though and giving an update on the release stuff!

**Comment by victoronline** [comment]
Sounds good. Thanks Jesse

**Pull request merged**
